// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56fi6aWgb_OkBz5YbwrZyAvJGcPk4sO4',
    appId: '1:71119375796:web:89821a222a606cd8fbb6e1',
    messagingSenderId: '71119375796',
    projectId: 'week10leon',
    authDomain: 'week10leon.firebaseapp.com',
    storageBucket: 'week10leon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoD9NqGvnk27jTs9GD-YxTdwAuSkvDWIw',
    appId: '1:71119375796:android:b62f9ea44e0fbd05fbb6e1',
    messagingSenderId: '71119375796',
    projectId: 'week10leon',
    storageBucket: 'week10leon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIkLDOIqCNelaun0aR_RZy4U7Qhl4_Kys',
    appId: '1:71119375796:ios:33e72ecedaf70935fbb6e1',
    messagingSenderId: '71119375796',
    projectId: 'week10leon',
    storageBucket: 'week10leon.firebasestorage.app',
    iosBundleId: 'com.example.week6workshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIkLDOIqCNelaun0aR_RZy4U7Qhl4_Kys',
    appId: '1:71119375796:ios:33e72ecedaf70935fbb6e1',
    messagingSenderId: '71119375796',
    projectId: 'week10leon',
    storageBucket: 'week10leon.firebasestorage.app',
    iosBundleId: 'com.example.week6workshop',
  );
}
